### ISSUE TITLE
Removing webhooks based on response

### ISSUE THREAD

**Issue by stulogy** [mpociot/captainhook#23]
We're using this with Zapier, but we'd like to remove the webhooks/subscriptions/zaps that are returning 401 (removed). 

Could we add some code to `TriggerWebhooksJob.php` around line 72 to the tune of this:

                    }, function ($request, $options, Promise $response) use ($log, $webhook) {
                    $response->then(function (ResponseInterface $response) use ($log, $webhook) {
                        $log->status = $response->getStatusCode();
                        $log->response = $response->getBody()->getContents();
                        $log->response_format = $log->payload_format = isset($response->getHeader('Content-Type')[0]) ? $response->getHeader('Content-Type')[0] : null;

                        $log->save();

                        // Retry this job if the webhook response didn't give us a HTTP 200 OK
                        if ($response->getStatusCode() != 200) {
                            $this->release(30);
                        }

                        // Delete the webhook if the reponse is returning HTTP 410 REMOVED
                        if ($response->getStatusCode() == 410) {
                            $webhook->delete();
                        }
                    });

**Comment by mpociot** [comment]
Hmm...I don't like the idea to hardcode this into the package.

Yeah - it makes sense to "delete" the webhook if it returns status code 410, but if it just disappears the information of that 410 status gets lost.

Maybe it would be better to have a custom callback that can defined in the config file which receives the webhook and the response object.

**Comment by stulogy** [comment]
I’m not sure what you mean by 'which receives the webhook and the response object’.

What part of the config would I do this in?

**Comment by mpociot** [comment]
It's currently not possible the way I described it.

I was thinking of an addition of the package where you could configure something like:

```php
// this would be inside the config file
return [

   'callback' => 'Foo@receiveWebhook'

]
```

And the `Foo` class would look like this:
```php
class Foo {
   public function receiveWebhook( $webhook, $response ) {
       // Handle your custom logic inside this method
       if ($response->getStatusCode() === 410) {
           $webhook->delete();
       }
   }
}
```

What do you think of this?

**Comment by stulogy** [comment]
Oh I see, yes that would be perfect.  A custom call back would be so useful and I’m sure lots of people who are using this for Zapier would benefit. Great package by the way!

**Comment by mpociot** [comment]
Please take a look at version 2.2.0
